<?php

/**
 * @copyright   Copyright (c) 2019-2022 Jeffrey Bostoen
 * @license     https://www.gnu.org/licenses/gpl-3.0.en.html
 * @version     2.7.221223
 *
 */

namespace JeffreyBostoenExtensions\ServerCommunication\Extensions;

use JeffreyBostoenExtensions\ServerCommunication\{
	eApiVersion,
	Helper,
	v200\HttpRequest as HttpRequest_200,
	v200\HttpResponse as HttpResponse_200,
	v210\HttpResponse as HttpResponse_210
};

/**
 * Class TokenServerExtension. Handles the token confirmation.
 * 
 * Note: By default, this will never be executed since the SupportsClient() method is not overruled and there are no supported operations.
 */
class TokenServerExtension extends ServerExtension {

	/**
	 * @inheritDoc
	 */
	public function GetRank() : int {
		return 999;
	}

	/**
	 * @inheritDoc
	 * 
	 * The base class supports all API versions where tokens have been implemented.
	 */
	public function GetSupportedApiVersions() : array {

		return [
			eApiVersion::v2_0_0,
			eApiVersion::v2_1_0,
		];

	}


	/**
	 * @inheritDoc
	 */ 
	public function Process() : void {

		$oResponse = $this->GetHttpResponse();
		$oRequest = $this->GetHttpRequest();

		if($oResponse !== null) {

			if($oRequest instanceof HttpRequest_200) {

				$sClientToken = $oRequest->token;
				$sNewClientToken = bin2hex(random_bytes(Helper::CLIENT_TOKEN_BYTES));

				/** @var HttpResponse_200 $oResponse */
				$oResponse->refresh_token = $sNewClientToken;

			}
			else {

				$sClientToken = $oRequest->client_token;
				$sNewClientToken = $oRequest->new_client_token;

				/** @var HttpResponse_210 $oResponse */
				$oResponse->new_client_token = $sNewClientToken;

			}

			Helper::Trace('Token: Authentication token = "%1$s", new token = "%2$s".', $sClientToken, $sNewClientToken);

			$this->SaveToken($sClientToken, $sNewClientToken);

		}

	}


	/**
	 * Save the token if needed.
	 * 
	 * @param string $sClientToken The current client token.
	 * @param string $sNewClientToken The new client token (in API 2.0.0: Generated by the server; in later versions: generated by the client).
	 *
	 * @return void
	 */
	public function SaveToken(string $sClientToken, string $sNewClientToken) : void {

		// Add some logic here.

	}


}
